### ISSUE TITLE
Html scraping of pepy tech

### ISSUE THREAD

**Issue by astrom-tom** [psincraian/pepy-front#1]
@psincraian 

As I think it is more appropriate to post it there here it is. I wrote this python package stpip that scrap pepy.tech (as I told you in the pepy backend repo). Now I see that the html code have changed and the numbers are not in the html code anymore. Do you have any idea how to get around that problem and how to get the download counts from your webpage?

**Comment by psincraian** [comment]
You can use the API: https://api.pepy.tech/api/projects/requests ☺

**Comment by astrom-tom** [comment]
Awesome! I could fix the module! Thanks!
