### ISSUE TITLE
https://pepy.tech/   Inaccessible

### ISSUE THREAD

**Issue by Pactortester** [psincraian/pepy-front#359]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/29191106/158506058-0297cde7-99df-4faf-9bfb-063fcefa4c6d.png">

**Comment by hotlittlewhitedog** [comment]
Domain is expired: 2022-03-10

**Comment by psincraian** [comment]
You can keep track of this issue here https://github.com/psincraian/pepy/issues/422
